In [4]:
import pandas as pd
df = pd.read_csv("01_account_targeting_leads (1).csv")
df.head()

      company industry  employee_count  engagement_score
0   AlphaTech     SaaS             250                85
1    BetaSoft  Fintech             120                60
2   CloudNine     SaaS             500                90
3  DataBridge     Data              80                40
4   NextGenAI       AI             300                75

In [5]:
df.info()
df.describe()
df['industry'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   company           10 non-null     object
 1   industry          10 non-null     object
 2   employee_count    10 non-null     int64
 3   engagement_score  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

industry
SaaS         4
Fintech      2
Data         1
AI           1
Marketing    1
Analytics    1
Name: count, dtype: int64

In [8]:
df = df.drop_duplicates()
df = df.dropna()

def score_lead(row):
    score = 0

    if row['industry'] == 'SaaS':
        score += 3
    if row['employee_count'] > 200:
        score += 2
    if row['engagement_score'] > 70:
        score += 5
    return score
df['lead_score'] = df.apply(score_lead, axis=1)

In [11]:
df = df.sort_values(by='lead_score', ascending=False)
df.head(10)

        company   industry  employee_count  engagement_score  lead_score
0     AlphaTech       SaaS             250                85          10
2     CloudNine       SaaS             500                90          10
7     SalesFlow       SaaS             400                92          10
8     GrowthHub       SaaS             600                78          10
4     NextGenAI         AI             300                75           7
5     Finlytics    Fintech             220                88           7
1      BetaSoft    Fintech             120                60           0
3    DataBridge       Data              80                40           0
6  MarketGenius  Marketing             150                55           0
9     InsightIQ  Analytics              90                50           0

In [12]:
df.to_csv("scored_leads.csv", index=False)

In [14]:
df.groupby('industry')['lead_score'].mean()

industry
AI            7.0
Analytics     0.0
Data          0.0
Fintech       3.5
Marketing     0.0
SaaS         10.0
Name: lead_score, dtype: float64